"""
Compare Python phasecongruency outputs against Julia reference outputs.

Usage:
    python compare_with_julia.py [julia_results_dir]

The julia_results_dir should contain .npy files generated by
generate_julia_results.jl. If not specified, defaults to ./julia_results/

Requires: numpy, scipy, phasecongruency (install from parent directory)
"""

import sys
import os
import numpy as np
from pathlib import Path

# Ensure the parent directory is on the path so we can import phasecongruency
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from phasecongruency import (
    filtergrids, filtergrid, monogenicfilters, packedmonogenicfilters,
    lowpassfilter, highpassfilter, bandpassfilter, highboostfilter,
    loggabor, gridangles, cosineangularfilter, gaussianangularfilter,
    perfft2, geoseries,
    step2line, circsine, starsine, noiseonf, quantizephase, nophase,
    histtruncate, imgnormalize, replacenan, hysthresh, fillnan,
    highpassmonogenic, bandpassmonogenic, ppdrc, phasecongmono,
    phasesymmono, phasecong3, phasesym, ppdenoise, monofilt, gaborconvolve,
)


# ======================================================================
# Helpers
# ======================================================================

def load(resultsdir, name):
    """Load a .npy file from the Julia results directory."""
    path = os.path.join(resultsdir, name + ".npy")
    if not os.path.exists(path):
        return None
    return np.load(path)


def compare(name, julia_arr, python_arr, atol=1e-10, rtol=1e-10):
    """Compare two arrays and return a result dict."""
    if julia_arr is None:
        return {"name": name, "status": "SKIP", "reason": "Julia file not found"}
    if python_arr is None:
        return {"name": name, "status": "SKIP", "reason": "Python result is None"}

    julia_arr = np.asarray(julia_arr, dtype=np.float64)
    python_arr = np.asarray(python_arr, dtype=np.float64)

    if julia_arr.shape != python_arr.shape:
        return {
            "name": name,
            "status": "FAIL",
            "reason": f"Shape mismatch: Julia {julia_arr.shape} vs Python {python_arr.shape}",
        }

    # Handle NaN: both NaN in same position is OK
    julia_nan = np.isnan(julia_arr)
    python_nan = np.isnan(python_arr)
    if not np.array_equal(julia_nan, python_nan):
        return {
            "name": name,
            "status": "FAIL",
            "reason": f"NaN positions differ ({julia_nan.sum()} vs {python_nan.sum()} NaNs)",
        }

    # Compare non-NaN values
    mask = ~julia_nan
    if mask.sum() == 0:
        return {"name": name, "status": "PASS", "maxdiff": 0.0}

    diff = np.abs(julia_arr[mask] - python_arr[mask])
    maxdiff = diff.max()
    meandiff = diff.mean()
    close = np.allclose(julia_arr[mask], python_arr[mask], atol=atol, rtol=rtol)

    return {
        "name": name,
        "status": "PASS" if close else "FAIL",
        "maxdiff": maxdiff,
        "meandiff": meandiff,
        "reason": "" if close else f"max diff {maxdiff:.2e}, mean diff {meandiff:.2e}",
    }


# ======================================================================
# Test groups
# ======================================================================

def compare_filtergrids(d):
    """Compare filtergrids outputs."""
    results = []
    for rows, cols in [(64, 64), (63, 63), (101, 200), (128, 100)]:
        f_py, fx_py, fy_py = filtergrids(rows, cols)
        results.append(compare(f"filtergrids_{rows}x{cols}_f", load(d, f"filtergrids_{rows}x{cols}_f"), f_py))
        results.append(compare(f"filtergrids_{rows}x{cols}_fx", load(d, f"filtergrids_{rows}x{cols}_fx"), fx_py))
        results.append(compare(f"filtergrids_{rows}x{cols}_fy", load(d, f"filtergrids_{rows}x{cols}_fy"), fy_py))
    return results


def compare_filtergrid(d):
    results = []
    for rows, cols in [(64, 64), (63, 63), (101, 200)]:
        f_py = filtergrid(rows, cols)
        results.append(compare(f"filtergrid_{rows}x{cols}", load(d, f"filtergrid_{rows}x{cols}"), f_py))
    return results


def compare_monogenicfilters(d):
    results = []
    for rows, cols in [(64, 64), (101, 200)]:
        H1, H2, f = monogenicfilters(rows, cols)
        tag = f"monofilters_{rows}x{cols}"
        results.append(compare(f"{tag}_H1_real", load(d, f"{tag}_H1_real"), H1.real))
        results.append(compare(f"{tag}_H1_imag", load(d, f"{tag}_H1_imag"), H1.imag))
        results.append(compare(f"{tag}_H2_real", load(d, f"{tag}_H2_real"), H2.real))
        results.append(compare(f"{tag}_H2_imag", load(d, f"{tag}_H2_imag"), H2.imag))
        results.append(compare(f"{tag}_f", load(d, f"{tag}_f"), f))
    return results


def compare_packedmonogenicfilters(d):
    results = []
    for rows, cols in [(64, 64), (101, 200)]:
        H, f = packedmonogenicfilters(rows, cols)
        tag = f"packedmono_{rows}x{cols}"
        results.append(compare(f"{tag}_H_real", load(d, f"{tag}_H_real"), H.real))
        results.append(compare(f"{tag}_H_imag", load(d, f"{tag}_H_imag"), H.imag))
        results.append(compare(f"{tag}_f", load(d, f"{tag}_f"), f))
    return results


def compare_lowpassfilter(d):
    results = []
    for rows, cols, cutoff, n in [(64, 64, 0.25, 2), (101, 200, 0.4, 15)]:
        f_py = lowpassfilter((rows, cols), cutoff, n)
        results.append(compare(f"lowpass_{rows}x{cols}_{cutoff}_{n}",
                               load(d, f"lowpass_{rows}x{cols}_{cutoff}_{n}"), f_py))
    return results


def compare_highpassfilter(d):
    f_py = highpassfilter((64, 64), 0.25, 2)
    return [compare("highpass_64x64_0.25_2", load(d, "highpass_64x64_0.25_2"), f_py)]


def compare_bandpassfilter(d):
    f_py = bandpassfilter((64, 64), 0.1, 0.3, 2)
    return [compare("bandpass_64x64_0.1_0.3_2", load(d, "bandpass_64x64_0.1_0.3_2"), f_py)]


def compare_highboostfilter(d):
    f_py = highboostfilter((64, 64), 0.25, 2, 2.0)
    return [compare("highboost_64x64_0.25_2_2.0", load(d, "highboost_64x64_0.25_2_2.0"), f_py)]


def compare_loggabor(d):
    results = []
    for fval, fo, sigma in [(0.0, 0.3, 0.55), (0.1, 0.3, 0.55), (0.3, 0.3, 0.55), (0.5, 0.3, 0.55)]:
        v_py = loggabor(fval, fo, sigma)
        jl = load(d, f"loggabor_{fval}_{fo}_{sigma}")
        # Julia saves scalars as [val], extract
        if jl is not None and jl.ndim == 1 and jl.size == 1:
            jl = jl[0]
        results.append(compare(f"loggabor_{fval}_{fo}_{sigma}", np.array([jl]), np.array([v_py])))
    return results


def compare_gridangles(d):
    f, fx, fy = filtergrids(64, 64)
    sintheta, costheta = gridangles(f, fx, fy)
    return [
        compare("gridangles_64x64_sin", load(d, "gridangles_64x64_sin"), sintheta),
        compare("gridangles_64x64_cos", load(d, "gridangles_64x64_cos"), costheta),
    ]


def compare_cosineangularfilter(d):
    f, fx, fy = filtergrids(64, 64)
    sintheta, costheta = gridangles(f, fx, fy)
    fltr = cosineangularfilter(np.pi / 4, np.pi / 3, sintheta, costheta)
    return [compare("cosangfilt_64x64", load(d, "cosangfilt_64x64"), fltr)]


def compare_gaussianangularfilter(d):
    f, fx, fy = filtergrids(64, 64)
    sintheta, costheta = gridangles(f, fx, fy)
    fltr = gaussianangularfilter(np.pi / 4, 0.4, sintheta, costheta)
    return [compare("gaussangfilt_64x64", load(d, "gaussangfilt_64x64"), fltr)]


def compare_perfft2(d, randimg):
    P, S, p, s = perfft2(randimg)
    return [
        compare("perfft2_P_real", load(d, "perfft2_P_real"), P.real),
        compare("perfft2_P_imag", load(d, "perfft2_P_imag"), P.imag),
        compare("perfft2_S_real", load(d, "perfft2_S_real"), S.real),
        compare("perfft2_S_imag", load(d, "perfft2_S_imag"), S.imag),
        compare("perfft2_p", load(d, "perfft2_p"), p),
        compare("perfft2_s", load(d, "perfft2_s"), s),
    ]


def compare_geoseries(d):
    s1 = geoseries(0.5, 2.0, 4)
    s2 = geoseries((0.5, 4.0), 4)
    return [
        compare("geoseries_0.5_2_4", load(d, "geoseries_0.5_2_4"), np.array(s1)),
        compare("geoseries_tuple_4", load(d, "geoseries_tuple_4"), np.array(s2)),
    ]


def compare_syntheticimages(d):
    results = []

    img64 = step2line(64, nscales=10)
    results.append(compare("step2line_64_10", load(d, "step2line_64_10"), img64))

    img128 = step2line(128)
    results.append(compare("step2line_128_default", load(d, "step2line_128_default"), img128))

    results.append(compare("step2line_custom",
                           load(d, "step2line_custom"),
                           step2line(128, nscales=20, ampexponent=-1.5, ncycles=3.0, phasecycles=0.5)))

    results.append(compare("circsine_64",
                           load(d, "circsine_64"),
                           circsine(64, wavelength=20, nscales=10)))

    results.append(compare("circsine_65_offset",
                           load(d, "circsine_65_offset"),
                           circsine(65, wavelength=40, nscales=1, offset=np.pi / 2)))

    results.append(compare("starsine_64",
                           load(d, "starsine_64"),
                           starsine(64, ncycles=10, nscales=10)))

    results.append(compare("starsine_65_offset",
                           load(d, "starsine_65_offset"),
                           starsine(65, ncycles=10, nscales=1, offset=0.0)))

    # noiseonf uses random - can only compare shape/range, not exact values
    jl_noise = load(d, "noiseonf_64_1.5")
    if jl_noise is not None:
        py_noise = noiseonf(64, 1.5)
        if jl_noise.shape == py_noise.shape:
            results.append({"name": "noiseonf_64_1.5", "status": "PASS",
                            "maxdiff": 0.0,
                            "reason": "Shape matches (random values differ by design)"})
        else:
            results.append({"name": "noiseonf_64_1.5", "status": "FAIL",
                            "reason": f"Shape mismatch: {jl_noise.shape} vs {py_noise.shape}"})

    return results


def compare_quantizephase(d, randimg):
    results = []
    qp_py = quantizephase(randimg, 4)
    results.append(compare("quantizephase_4", load(d, "quantizephase_4"), qp_py))
    return results


def compare_utilities(d, randimg):
    results = []

    # histtruncate
    results.append(compare("histtruncate_10_10",
                           load(d, "histtruncate_10_10"),
                           histtruncate(randimg, 10.0, 10.0)))
    results.append(compare("histtruncate_5",
                           load(d, "histtruncate_5"),
                           histtruncate(randimg, 5.0)))

    # imgnormalize
    results.append(compare("imgnormalize_01",
                           load(d, "imgnormalize_01"),
                           imgnormalize(randimg)))
    results.append(compare("imgnormalize_mv",
                           load(d, "imgnormalize_mv"),
                           imgnormalize(randimg, 5.0, 2.0)))

    # replacenan
    nanimg = randimg.copy()
    nanimg[9:20, 9:20] = np.nan  # Julia 10:20 is 1-indexed = Python 9:20
    newimg, mask = replacenan(nanimg, 99.0)
    results.append(compare("replacenan_img", load(d, "replacenan_img"), newimg))
    results.append(compare("replacenan_mask", load(d, "replacenan_mask"), mask.astype(np.float64)))

    # hysthresh
    htimg = np.zeros((30, 30))
    htimg[2:25, 14] = 5.0   # Julia 3:25 row, 15 col → Python 2:25, 14
    htimg[7:12, 14] = 10.0  # Julia 8:12 → Python 7:12
    htimg[14:20, 14] = 10.0  # Julia 15:20 → Python 14:20
    htimg[14, 14] = 20.0     # Julia [15,15] → Python [14,14]
    bw = hysthresh(htimg, 8.0, 20.0)
    results.append(compare("hysthresh_result", load(d, "hysthresh_result"), bw.astype(np.float64)))

    # fillnan
    nanimg2 = randimg[:20, :20].copy().astype(np.float64)
    nanimg2[4:10, 4:10] = np.nan  # Julia 5:10 → Python 4:10
    newimg2, mask2 = fillnan(nanimg2)
    results.append(compare("fillnan_img", load(d, "fillnan_img"), newimg2, atol=1e-8, rtol=1e-8))
    results.append(compare("fillnan_mask", load(d, "fillnan_mask"), mask2.astype(np.float64)))

    return results


def compare_phasecongruency_funcs(d, randimg32):
    results = []

    # highpassmonogenic
    ph, orient, E = highpassmonogenic(randimg32, 20.0, 4)
    results.append(compare("highpassmono_phase", load(d, "highpassmono_phase"), ph, atol=1e-8, rtol=1e-8))
    results.append(compare("highpassmono_orient", load(d, "highpassmono_orient"), orient, atol=1e-8, rtol=1e-8))
    results.append(compare("highpassmono_E", load(d, "highpassmono_E"), E, atol=1e-8, rtol=1e-8))

    # bandpassmonogenic
    ph, orient, E = bandpassmonogenic(randimg32, 4.0, 20.0, 4)
    results.append(compare("bandpassmono_phase", load(d, "bandpassmono_phase"), ph, atol=1e-8, rtol=1e-8))
    results.append(compare("bandpassmono_orient", load(d, "bandpassmono_orient"), orient, atol=1e-8, rtol=1e-8))
    results.append(compare("bandpassmono_E", load(d, "bandpassmono_E"), E, atol=1e-8, rtol=1e-8))

    # ppdrc single
    dimg = ppdrc(randimg32 * 100, 20.0, clip=0.01, n=2)
    results.append(compare("ppdrc_single", load(d, "ppdrc_single"), dimg, atol=1e-8, rtol=1e-8))

    # ppdrc multi
    dimgs = ppdrc(randimg32 * 100, geoseries((10.0, 30.0), 3), clip=0.01, n=2)
    jl_count = load(d, "ppdrc_multi_count")
    if jl_count is not None:
        n_expected = int(jl_count[0]) if jl_count.ndim == 1 else int(jl_count)
        if len(dimgs) != n_expected:
            results.append({"name": "ppdrc_multi_count", "status": "FAIL",
                            "reason": f"Count mismatch: Julia {n_expected} vs Python {len(dimgs)}"})
        else:
            results.append({"name": "ppdrc_multi_count", "status": "PASS", "maxdiff": 0.0})
    for i, d_img in enumerate(dimgs):
        results.append(compare(f"ppdrc_multi_{i+1}", load(d, f"ppdrc_multi_{i+1}"), d_img, atol=1e-8, rtol=1e-8))

    # phasecongmono
    PC, or_pcm, ft, T_pcm = phasecongmono(randimg32, nscale=3, minwavelength=3, mult=2.0,
                                            sigmaonf=0.55, k=3.0, noisemethod=-1.0,
                                            cutoff=0.5, g=10.0, deviationgain=1.5)
    results.append(compare("phasecongmono_PC", load(d, "phasecongmono_PC"), PC, atol=1e-8, rtol=1e-8))
    results.append(compare("phasecongmono_or", load(d, "phasecongmono_or"), or_pcm, atol=1e-8, rtol=1e-8))
    results.append(compare("phasecongmono_ft", load(d, "phasecongmono_ft"), ft, atol=1e-8, rtol=1e-8))
    results.append(compare("phasecongmono_T", load(d, "phasecongmono_T"), np.atleast_1d(T_pcm), atol=1e-8, rtol=1e-8))

    # phasesymmono
    phSym, symE, T_psm = phasesymmono(randimg32, nscale=3, minwavelength=3, mult=2.0,
                                        sigmaonf=0.55, k=2.0, polarity=0, noisemethod=-1.0)
    results.append(compare("phasesymmono_phSym", load(d, "phasesymmono_phSym"), phSym, atol=1e-8, rtol=1e-8))
    results.append(compare("phasesymmono_symE", load(d, "phasesymmono_symE"), symE, atol=1e-8, rtol=1e-8))
    results.append(compare("phasesymmono_T", load(d, "phasesymmono_T"), np.atleast_1d(T_psm), atol=1e-8, rtol=1e-8))

    # phasecong3
    M, m, or_pc3, featType, EO, T_pc3 = phasecong3(randimg32, nscale=3, norient=4,
                                                      minwavelength=3, mult=2.0,
                                                      sigmaonf=0.55, k=2.0,
                                                      cutoff=0.5, g=10.0, noisemethod=-1.0)
    jl_M = load(d, "phasecong3_Mmax")
    if jl_M is None:
        jl_M = load(d, "phasecong3_M")
    jl_m = load(d, "phasecong3_mmin")
    if jl_m is None:
        jl_m = load(d, "phasecong3_m")
    results.append(compare("phasecong3_M", jl_M, M, atol=1e-8, rtol=1e-8))
    results.append(compare("phasecong3_m", jl_m, m, atol=1e-8, rtol=1e-8))
    results.append(compare("phasecong3_or", load(d, "phasecong3_or"), or_pc3, atol=1e-8, rtol=1e-8))
    results.append(compare("phasecong3_ft", load(d, "phasecong3_ft"), featType, atol=1e-8, rtol=1e-8))
    results.append(compare("phasecong3_T", load(d, "phasecong3_T"), np.atleast_1d(T_pc3), atol=1e-8, rtol=1e-8))

    # EO slices
    results.append(compare("phasecong3_EO_1_1_real", load(d, "phasecong3_EO_1_1_real"),
                           EO[0][0].real, atol=1e-8, rtol=1e-8))
    results.append(compare("phasecong3_EO_1_1_imag", load(d, "phasecong3_EO_1_1_imag"),
                           EO[0][0].imag, atol=1e-8, rtol=1e-8))
    results.append(compare("phasecong3_EO_2_3_real", load(d, "phasecong3_EO_2_3_real"),
                           EO[1][2].real, atol=1e-8, rtol=1e-8))
    results.append(compare("phasecong3_EO_2_3_imag", load(d, "phasecong3_EO_2_3_imag"),
                           EO[1][2].imag, atol=1e-8, rtol=1e-8))

    # phasesym
    phSym2, orient2, totE, T_ps = phasesym(randimg32, nscale=3, norient=4,
                                             minwavelength=3, mult=2.0, sigmaonf=0.55,
                                             k=2.0, polarity=0, noisemethod=-1.0)
    results.append(compare("phasesym_phSym", load(d, "phasesym_phSym"), phSym2, atol=1e-8, rtol=1e-8))
    results.append(compare("phasesym_orient", load(d, "phasesym_orient"), orient2, atol=1e-8, rtol=1e-8))
    results.append(compare("phasesym_totE", load(d, "phasesym_totE"), totE, atol=1e-8, rtol=1e-8))
    results.append(compare("phasesym_T", load(d, "phasesym_T"), np.atleast_1d(T_ps), atol=1e-8, rtol=1e-8))

    # ppdenoise
    clean = ppdenoise(randimg32, nscale=3, norient=4, mult=2.5,
                       minwavelength=2, sigmaonf=0.55,
                       dthetaonsigma=1.0, k=3.0, softness=1.0)
    results.append(compare("ppdenoise_clean", load(d, "ppdenoise_clean"), clean, atol=1e-8, rtol=1e-8))

    # monofilt
    f_mf, h1f_mf, h2f_mf, A_mf, theta_mf, psi_mf = monofilt(randimg32, 3, 3, 2.0, 0.55, False)
    for s in range(3):
        results.append(compare(f"monofilt_f_{s+1}", load(d, f"monofilt_f_{s+1}"), f_mf[s], atol=1e-8, rtol=1e-8))
        results.append(compare(f"monofilt_h1f_{s+1}", load(d, f"monofilt_h1f_{s+1}"), h1f_mf[s], atol=1e-8, rtol=1e-8))
        results.append(compare(f"monofilt_h2f_{s+1}", load(d, f"monofilt_h2f_{s+1}"), h2f_mf[s], atol=1e-8, rtol=1e-8))
        results.append(compare(f"monofilt_A_{s+1}", load(d, f"monofilt_A_{s+1}"), A_mf[s], atol=1e-8, rtol=1e-8))
        results.append(compare(f"monofilt_theta_{s+1}", load(d, f"monofilt_theta_{s+1}"), theta_mf[s], atol=1e-8, rtol=1e-8))
        results.append(compare(f"monofilt_psi_{s+1}", load(d, f"monofilt_psi_{s+1}"), psi_mf[s], atol=1e-8, rtol=1e-8))

    # gaborconvolve
    EO_gc, BP_gc = gaborconvolve(randimg32, 3, 4, 3, 2.0, 0.55, 1.3, 0)
    for s in range(3):
        results.append(compare(f"gabor_BP_{s+1}", load(d, f"gabor_BP_{s+1}"), BP_gc[s], atol=1e-8, rtol=1e-8))
        for o in range(4):
            results.append(compare(f"gabor_EO_{s+1}_{o+1}_real",
                                   load(d, f"gabor_EO_{s+1}_{o+1}_real"),
                                   EO_gc[s][o].real, atol=1e-8, rtol=1e-8))
            results.append(compare(f"gabor_EO_{s+1}_{o+1}_imag",
                                   load(d, f"gabor_EO_{s+1}_{o+1}_imag"),
                                   EO_gc[s][o].imag, atol=1e-8, rtol=1e-8))

    return results


# ======================================================================
# Main
# ======================================================================

def main():
    resultsdir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "julia_results")

    if not os.path.isdir(resultsdir):
        print(f"ERROR: Julia results directory not found: {resultsdir}")
        print("Run generate_julia_results.jl first to create reference outputs.")
        sys.exit(1)

    npy_files = [f for f in os.listdir(resultsdir) if f.endswith(".npy")]
    print(f"Found {len(npy_files)} .npy files in {resultsdir}")
    print("=" * 70)

    # Load shared test data
    randimg = load(resultsdir, "randimg_64")
    randimg32 = load(resultsdir, "randimg_32")

    if randimg is None or randimg32 is None:
        print("ERROR: randimg_64.npy or randimg_32.npy not found. Run Julia script first.")
        sys.exit(1)

    all_results = []

    # 1. Frequency filters
    print("\n--- Frequency Filters ---")
    all_results.extend(compare_filtergrids(resultsdir))
    all_results.extend(compare_filtergrid(resultsdir))
    all_results.extend(compare_monogenicfilters(resultsdir))
    all_results.extend(compare_packedmonogenicfilters(resultsdir))
    all_results.extend(compare_lowpassfilter(resultsdir))
    all_results.extend(compare_highpassfilter(resultsdir))
    all_results.extend(compare_bandpassfilter(resultsdir))
    all_results.extend(compare_highboostfilter(resultsdir))
    all_results.extend(compare_loggabor(resultsdir))
    all_results.extend(compare_gridangles(resultsdir))
    all_results.extend(compare_cosineangularfilter(resultsdir))
    all_results.extend(compare_gaussianangularfilter(resultsdir))
    all_results.extend(compare_perfft2(resultsdir, randimg))
    all_results.extend(compare_geoseries(resultsdir))

    # 2. Synthetic images
    print("\n--- Synthetic Images ---")
    all_results.extend(compare_syntheticimages(resultsdir))
    all_results.extend(compare_quantizephase(resultsdir, randimg))

    # 3. Utilities
    print("\n--- Utilities ---")
    all_results.extend(compare_utilities(resultsdir, randimg))

    # 4. Phase congruency functions
    print("\n--- Phase Congruency ---")
    all_results.extend(compare_phasecongruency_funcs(resultsdir, randimg32))

    # Print results
    print("\n" + "=" * 70)
    print(f"{'Test':<45} {'Status':<8} {'Max Diff':<12} {'Notes'}")
    print("-" * 90)

    n_pass = 0
    n_fail = 0
    n_skip = 0

    for r in all_results:
        status = r["status"]
        name = r["name"]
        maxdiff = r.get("maxdiff", "")
        reason = r.get("reason", "")

        if status == "PASS":
            n_pass += 1
            maxdiff_str = f"{maxdiff:.2e}" if isinstance(maxdiff, float) else str(maxdiff)
            print(f"  {name:<45} PASS     {maxdiff_str:<12}")
        elif status == "FAIL":
            n_fail += 1
            print(f"  {name:<45} FAIL     {'':12} {reason}")
        else:
            n_skip += 1
            print(f"  {name:<45} SKIP     {'':12} {reason}")

    print("\n" + "=" * 70)
    print(f"TOTAL: {len(all_results)} tests  |  PASS: {n_pass}  |  FAIL: {n_fail}  |  SKIP: {n_skip}")

    if n_fail > 0:
        print("\nFAILED TESTS:")
        for r in all_results:
            if r["status"] == "FAIL":
                print(f"  - {r['name']}: {r.get('reason', '')}")
        print()
        sys.exit(1)
    elif n_skip > 0 and n_pass == 0:
        print("\nNo Julia results found — all tests skipped.")
        print("Run generate_julia_results.jl first.")
        sys.exit(1)
    else:
        print("\nAll comparisons PASSED!")
        sys.exit(0)


if __name__ == "__main__":
    main()
